# Generated by Django 5.0.3 on 2024-03-27 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malgrave_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.AddField(
            model_name='character',
            name='armour_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='empty', max_length=300),
        ),
        migrations.AddField(
            model_name='character',
            name='health_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default='none', upload_to='character_images/'),
        ),
        migrations.AddField(
            model_name='character',
            name='mental_scars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='character',
            name='stress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='valors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
