# Generated by Django 5.0.3 on 2024-03-27 23:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malgrave_characters', '0002_alter_character_character_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mental_scars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='valors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
    ]
