# Generated by Django 5.0.3 on 2024-03-27 23:06

import django.contrib.postgres.fields
import malgrave_characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malgrave_characters', '0003_alter_character_mental_scars_alter_character_valors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mental_scars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=malgrave_characters.models.default_array, size=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='valors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=malgrave_characters.models.default_array, size=None),
        ),
    ]
