# Generated by Django 5.0.3 on 2024-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malgrave_characters', '0004_alter_character_mental_scars_alter_character_valors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(default='none', upload_to='character-images/'),
        ),
    ]
