# Generated by Django 5.0.3 on 2024-04-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malgrave_characters', '0007_alter_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
